# Generated by Django 4.2.6 on 2023-10-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.FileField(default=None, upload_to='event_images/'),
        ),
    ]
