# Generated by Django 4.2.6 on 2023-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
