# Generated by Django 4.2.6 on 2023-11-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_fee',
            field=models.IntegerField(default=0),
        ),
    ]
