# Generated by Django 4.2.7 on 2023-11-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_event_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_details',
            field=models.TextField(default='im vinay'),
        ),
    ]
