# Generated by Django 4.2.7 on 2023-11-16 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_description', models.TextField()),
                ('host_details', models.TextField(default='Tell about yourself')),
                ('room_time', models.DateTimeField()),
                ('room_location', models.CharField(max_length=255)),
                ('room_fee', models.IntegerField(default=0)),
                ('room_image', models.ImageField(default='room_images/default_image.webp', upload_to='room_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Registration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room')},
            },
        ),
    ]
