# Generated by Django 4.2.7 on 2023-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_hotel_hotelbooking_delete_registration2_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.IntegerField(default=10),
        ),
    ]
